alias erase-gems='for gem in `gem list | cut -d " " -f 1`; do yes | gem uninstall $gem -a; done'
alias b='bundle'
alias bi='b install --path .bundle'
alias bil='bi --local'
alias be='b exec'
alias bu='b update'
alias sc='script/rails console'
alias sg='script/rails generate'
alias ss='script/rails server'
alias migrate='rake db:migrate'
alias re='rbenv'
alias rr='rbenv rehash'
alias rbinst='CONFIGURE_OPTS="--with-readline-dir=/usr/local --with-openssl-dir=/usr/local" rbenv install'
alias restart-con-app!='touch ~/.pow/con-app/tmp/restart.txt'
alias restart-review-con-app!='touch ~/.pow/review-con-app/tmp/restart.txt'