alias erase-gems='for gem in `gem list | cut -d " " -f 1`; do yes | gem uninstall $gem -a; done'
alias b='bundle exec'
alias bi='bundle install --path .bundle'
alias bil='bundle install --path .bundle --local'
alias bu='bundle update'
alias rc='rails console'
alias rg='rails generate'
alias rs='rails server'
alias rr='rbenv rehash'
alias rbinst='CONFIGURE_OPTS="--with-readline-dir=/usr/local --with-openssl-dir=/usr/local" rbenv install'
alias ru='rackup $HOME/.config.ru'
alias pf='powify'
alias fs='foreman start'

alias devlog='tail -f log/development.log'
alias prodlog='tail -f log/production.log'
alias testlog='tail -f log/test.log'

alias -g RED='RAILS_ENV=development'
alias -g REP='RAILS_ENV=production'
alias -g RET='RAILS_ENV=test'

alias rdm='rake db:migrate'
alias rdr='rake db:rollback'
alias rdc='rake db:create'
alias rds='rake db:seed'
alias rdd='rake db:drop'
